version: '3'

services:
  pupils:
    container_name: pupils
    image: duranx/pupils
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=pupils
      - DATABASE_USERNAME=pupils
      - DATABASE_PASSWORD=pupils
    ports:
      - 1337:1337
    volumes:
      - ./app:/srv/app
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pupils
      POSTGRES_PASSWORD: pupils
      POSTGRES_DB: pupils
